sign-tag = true
shared-version = true
consolidate-commits = false
pre-release-commit-message = "[oxide-update-engine] version {{version}}"
tag-message = "[oxide-update-engine] version {{version}}"
tag-name = "oxide-update-engine-{{version}}"
publish = false
dependent-version = "upgrade"
pre-release-hook = ["just", "generate-readmes"]
