// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Errors generated by the engine crate.

use derive_where::derive_where;
use oxide_update_engine_types::{
    events::Event,
    spec::{AsError, StepSpec},
};
use std::{borrow::Cow, error, fmt};
use tokio::sync::mpsc;

/// An error that occurs while the engine is being executed.
#[derive_where(Debug)]
pub enum ExecutionError<S: StepSpec> {
    StepFailed {
        component: S::Component,
        id: S::StepId,
        description: Cow<'static, str>,
        error: S::Error,
    },
    Aborted {
        component: S::Component,
        id: S::StepId,
        description: Cow<'static, str>,
        message: String,
    },
    EventSendError(mpsc::error::SendError<Event<S>>),
}

impl<S: StepSpec> fmt::Display for ExecutionError<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::StepFailed { description, .. } => {
                write!(f, "step failed: {description}")
            }
            Self::Aborted { description, message, .. } => {
                write!(
                    f,
                    "execution aborted while running step \
                     \"{description}\": {message}"
                )
            }
            Self::EventSendError(_) => {
                write!(f, "while sending event, event receiver dropped")
            }
        }
    }
}

impl<S: StepSpec> error::Error for ExecutionError<S> {
    fn source(&self) -> Option<&(dyn error::Error + 'static)> {
        match self {
            ExecutionError::StepFailed { error, .. } => Some(error.as_error()),
            ExecutionError::Aborted { .. } => None,
            ExecutionError::EventSendError(error) => {
                Some(error as &(dyn error::Error + 'static))
            }
        }
    }
}

impl<S: StepSpec> From<mpsc::error::SendError<Event<S>>> for ExecutionError<S> {
    fn from(value: mpsc::error::SendError<Event<S>>) -> Self {
        Self::EventSendError(value)
    }
}
